### ISSUE TITLE
Create compat recipes are broken due to wrong location

### ISSUE THREAD

**Issue by ssfwuu0721** [axperty/moredelight-forge#11]
forge1.20.1-24.09.27
recipes should be placed in data/modid/recipes/

**Comment by axperty** [comment]
Hi ssfwuu0721,

I'll make this change so it works again.

Have a good day,
Axperty.

**Comment by ssfwuu0721** [comment]
> Hi ssfwuu0721,
> 
> I'll make this change so it works again.
> 
> Have a good day, Axperty.

oh i made a mistake. just recipes of create missing the folder named "recipes" that are broken. sorry

**Comment by axperty** [comment]
Hi ssfwuu0721,

An update has been released fixing this issue, thank you so much!

Have a good day,
Axperty.
