### ISSUE TITLE
Chicken Salad recipe

### ISSUE THREAD

**Issue by West8777** [axperty/moredelight-forge#2]
Chicken Salad doesn't require a bowl to craft but gives a bowl back when consumed. Since it only stacks to 16 I think it's intended to require a bowl, similar to the other FD salads, but currently doesn't.

**Comment by axperty** [comment]
Hi West8777,

Thank you for noticing this, I'll change the recipe to require a bowl.

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi West8777,

I just added this in the next update, stay tuned, it's coming really soon!

Have a good day,
Axperty.
