### ISSUE TITLE
Incompatibility: Casualness Delight

### ISSUE THREAD

**Issue by Handrail9** [axperty/moredelight-forge#4]
Hi, I was working on making a modpack for myself and I noticed that your mod and Casualness Delight have a recipe conflict. They both use potatoes on the cutting board. Was wondering if there was anything that could be done to fix the issue? 
Thanks
[Related Issue](https://github.com/TobishiroGinko/Casualness-Delight/issues/14#issue-2454944572)

**Comment by axperty** [comment]
Hi Handrail9,

There shouldn't be any issues with Casualness Delight as I made More Delight compatible with that mod.

If you have any more questions, please let me know. 

Have a good day, 
Axperty.

**Comment by Handrail9** [comment]
Hi axperty, I'm sorry if I'm misunderstanding something but while your mod does attempt to add compatibility, it doesn't appear to be complete 1:1. Your mod has the "Diced Potato" item which is used in 4 pages of cooking recipes, while Casualness Delight has "Sliced Potato" which is only used in 2 pages of cooking recipes. My instance of MC has chosen Casuallness's "Sliced Potato" over More Delight's "Diced Potato", thereby locking me out of about 2 pages of recipes. Attaching screenshots below.
JEI showing 4 pages of diced potatoes
![Screenshot_20240808_101734](https://github.com/user-attachments/assets/190de4ab-f5cc-4473-9f8a-5d07da5743de)
JEI showing only 2 pages of sliced potatoes
![Screenshot_20240808_101720](https://github.com/user-attachments/assets/7896420d-340f-447e-9657-e5e955e9e30c)
JEI showing an item that can only be made with More Delight
![Screenshot_20240808_101602](https://github.com/user-attachments/assets/428f11b5-3dde-4c8c-8b37-b158a59bfa7a)

I don't know if there's a way for me to "prioritize" More Delight recipes so the compatibility works correctly, if there's something that can be done on your end to "prioritize" it, or if theres a way to make Casualness sliced have the same NBT data as diced so you don't have to worry about which one get's loaded in, but currently I'm not able to access most diced potato recipes in your mod. :(

**Comment by axperty** [comment]
I understand now, I'll work to make More Delight fully compatible with Casualness Delight in the next update.

**Comment by That1Gamer64** [comment]
If I could pitch a suggestion to fix this issue, maybe the easiest thing would to allow for sliced potatoes to be used to create diced potatoes? I feel like that’d be the easiest way to do it that shouldn’t cause issues. (I wanted to try do it myself to try see if I can at least make a temporary fix but idk how to add/edit tags)

**Comment by axperty** [comment]
Hi That1Gamer64,

This is actually a good idea, I'll put this in the next update that I'll release this week.

Have a good day,
Axperty.
