### ISSUE TITLE
food category is not valid for crafting recipes

### ISSUE THREAD

**Issue by VendoAU** [axperty/moredelight-forge#5]
`food` is only a valid category for smelting or smoking.
It should be changed to `misc` for other recipies that need a category.
This also causes errors when using KubeJS, which is this mod's fault.

More info:
https://minecraft.wiki/w/Recipe

**Comment by axperty** [comment]
Hi Vendo AU,

I'll release an update today fixing this, thank you for letting me know. 

Have a good day, 
Axperty.
