### ISSUE TITLE
Bread slice conflict with Extra Delight

### ISSUE THREAD

**Issue by diamond-boots** [axperty/moredelight-forge#7]
When combined with Extra Delight, the bread slicing recipe stops working as the recipe overlaps.

**Comment by axperty** [comment]
Hi diamond-boots,

I'll work on compatibility for it.

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi diamond-boots,

I just took a look at this, I launched Minecraft with only Farmer's Delight and Extra Delight installed but it seems like this error is caused by Extra Delight itself. I'm not really sure what might be causing it.

Have a good day,
Axperty.
